apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: dataviv-backend:latest
        imagePullPolicy: Never  # Add this line to use local image
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:password@postgres:5432/auth_db"
        - name: SECRET_KEY
          value: "tempkey123"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "1"
        - name: REFRESH_TOKEN_EXPIRE_DAYS
          value: "7"
        ports:
        - containerPort: 8001
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
  - port: 8001
    targetPort: 8001
  type: ClusterIP
